spring:
  config:
    import: classpath:application-security.yml


  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/Game?serverTimezone=UTC&characterEncoding=UTF-8;
    username: ${spring.database.username}
    password: ${spring.database.password}

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: false
        show_sql: false
        use_sql_comments: false
        ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    com.zaxxer.hikari.HikariDataSource: OFF
    com.zaxxer.hikari.pool.HikariPool: OFF

file:
  upload-dir: F:\Spring\Game\Upload
