spring:
  config:
    import: classpath:application-security.yml


  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/Game?serverTimezone=UTC&characterEncoding=UTF-8;
    username: ${spring.database.username}
    password: ${spring.database.password}

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true
        ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB


file:
  upload-dir: F:\Spring\Game\Upload
